---
- name: "Create empty groups list ..."
  set_fact:
    my_groups: []

- name: "Append group {{ group_append.key | default(omit) }} to the group list ..."
  set_fact:
    my_groups: "{{ my_groups + [ group_append.key ] }}"
  loop: "{{ wum_groups | dict2items }}"
  loop_control:
    loop_var: group_append
    label: "{{ group_append }}"
