---
- name: "Find removed keys..."
  find:
    path: "{{ ssh_pool_dir }}"
    file_type: file
    excludes: "{{ wum_users.keys() }}"
  register: remove_keys

- name: "Delete removed keys..."
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ remove_keys['files'] }}"
