- name: "site / apply / docker / cleanup ..."
  include_role:
      name: wyga/site/docker/cleanup

- name: "site / apply / gitlab / runner ..."
  include_role:
      name: wyga/site/gitlab/runner
  when: host.setup.site.gitlab is defined and host.setup.site.gitlab.runner is defined
